name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:packages

      - name: Test
        run: yarn test

      - name: Publish to npm
        run: npm publish ./packages/perfect-freehand --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
